name = "lokaya-admin-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
NEXT_PUBLIC_APP_NAME = "Lokaya Admin"
NEXT_PUBLIC_API_URL = "https://api.lokaya.shop/api/v1"
NEXT_PUBLIC_BACKEND_URL = "https://api.lokaya.shop"
NEXT_PUBLIC_SOCKET_URL = "https://api.lokaya.shop"
NEXT_PUBLIC_CDN_DOMAIN = "https://7158d01d5e0dd9e7f5be050ed3717b14.r2.cloudflarestorage.com/lokaya-cdn"
