const { PrismaClient } = require('./prisma/client');
const prisma = new PrismaClient();

const GLOBAL_COUNTRY_FUEL_DATA = [
  // South Asia
  { countryCode: 'NP', countryName: 'Nepal', currency: 'NPR', currencySymbol: 'रू', fuelPricePerLiter: 200.00 },
  { countryCode: 'IN', countryName: 'India', currency: 'INR', currencySymbol: '₹', fuelPricePerLiter: 102.12 },
  { countryCode: 'BD', countryName: 'Bangladesh', currency: 'BDT', currencySymbol: '৳', fuelPricePerLiter: 130.00 },
  { countryCode: 'PK', countryName: 'Pakistan', currency: 'PKR', currencySymbol: 'Rs', fuelPricePerLiter: 275.60 },
  { countryCode: 'LK', countryName: 'Sri Lanka', currency: 'LKR', currencySymbol: 'Rs', fuelPricePerLiter: 355.00 },
  { countryCode: 'BT', countryName: 'Bhutan', currency: 'BTN', currencySymbol: 'Nu.', fuelPricePerLiter: 88.50 },
  { countryCode: 'MV', countryName: 'Maldives', currency: 'MVR', currencySymbol: 'Rf', fuelPricePerLiter: 16.50 },
  { countryCode: 'AF', countryName: 'Afghanistan', currency: 'AFN', currencySymbol: 'Af', fuelPricePerLiter: 68.00 },

  // Middle East & GCC
  { countryCode: 'AE', countryName: 'United Arab Emirates', currency: 'AED', currencySymbol: 'AED', fuelPricePerLiter: 3.03 },
  { countryCode: 'SA', countryName: 'Saudi Arabia', currency: 'SAR', currencySymbol: 'SAR', fuelPricePerLiter: 2.33 },
  { countryCode: 'QA', countryName: 'Qatar', currency: 'QAR', currencySymbol: 'QR', fuelPricePerLiter: 2.10 },
  { countryCode: 'OM', countryName: 'Oman', currency: 'OMR', currencySymbol: 'OMR', fuelPricePerLiter: 0.239 },
  { countryCode: 'KW', countryName: 'Kuwait', currency: 'KWD', currencySymbol: 'KD', fuelPricePerLiter: 0.105 },
  { countryCode: 'BH', countryName: 'Bahrain', currency: 'BHD', currencySymbol: 'BD', fuelPricePerLiter: 0.200 },
  { countryCode: 'IL', countryName: 'Israel', currency: 'ILS', currencySymbol: '₪', fuelPricePerLiter: 7.50 },
  { countryCode: 'JO', countryName: 'Jordan', currency: 'JOD', currencySymbol: 'JD', fuelPricePerLiter: 0.95 },
  { countryCode: 'LB', countryName: 'Lebanon', currency: 'LBP', currencySymbol: 'L£', fuelPricePerLiter: 82000.00 },
  { countryCode: 'TR', countryName: 'Turkey', currency: 'TRY', currencySymbol: '₺', fuelPricePerLiter: 43.50 },
  { countryCode: 'IQ', countryName: 'Iraq', currency: 'IQD', currencySymbol: 'IQD', fuelPricePerLiter: 750.00 },
  { countryCode: 'IR', countryName: 'Iran', currency: 'IRR', currencySymbol: 'IRR', fuelPricePerLiter: 30000.00 },
  { countryCode: 'YE', countryName: 'Yemen', currency: 'YER', currencySymbol: 'YR', fuelPricePerLiter: 500.00 },

  // Southeast & East Asia
  { countryCode: 'SG', countryName: 'Singapore', currency: 'SGD', currencySymbol: 'S$', fuelPricePerLiter: 2.85 },
  { countryCode: 'MY', countryName: 'Malaysia', currency: 'MYR', currencySymbol: 'RM', fuelPricePerLiter: 2.05 },
  { countryCode: 'TH', countryName: 'Thailand', currency: 'THB', currencySymbol: '฿', fuelPricePerLiter: 38.50 },
  { countryCode: 'ID', countryName: 'Indonesia', currency: 'IDR', currencySymbol: 'Rp', fuelPricePerLiter: 13500.00 },
  { countryCode: 'PH', countryName: 'Philippines', currency: 'PHP', currencySymbol: '₱', fuelPricePerLiter: 62.00 },
  { countryCode: 'VN', countryName: 'Vietnam', currency: 'VND', currencySymbol: '₫', fuelPricePerLiter: 23500.00 },
  { countryCode: 'JP', countryName: 'Japan', currency: 'JPY', currencySymbol: '¥', fuelPricePerLiter: 175.00 },
  { countryCode: 'KR', countryName: 'South Korea', currency: 'KRW', currencySymbol: '₩', fuelPricePerLiter: 1680.00 },
  { countryCode: 'CN', countryName: 'China', currency: 'CNY', currencySymbol: '¥', fuelPricePerLiter: 8.20 },
  { countryCode: 'HK', countryName: 'Hong Kong', currency: 'HKD', currencySymbol: 'HK$', fuelPricePerLiter: 24.50 },
  { countryCode: 'TW', countryName: 'Taiwan', currency: 'TWD', currencySymbol: 'NT$', fuelPricePerLiter: 31.50 },
  { countryCode: 'MM', countryName: 'Myanmar', currency: 'MMK', currencySymbol: 'K', fuelPricePerLiter: 2800.00 },
  { countryCode: 'KH', countryName: 'Cambodia', currency: 'KHR', currencySymbol: '៛', fuelPricePerLiter: 4400.00 },
  { countryCode: 'LA', countryName: 'Laos', currency: 'LAK', currencySymbol: '₭', fuelPricePerLiter: 27000.00 },
  { countryCode: 'BN', countryName: 'Brunei', currency: 'BND', currencySymbol: 'B$', fuelPricePerLiter: 0.53 },
  { countryCode: 'MN', countryName: 'Mongolia', currency: 'MNT', currencySymbol: '₮', fuelPricePerLiter: 2400.00 },

  // North America
  { countryCode: 'US', countryName: 'United States', currency: 'USD', currencySymbol: '$', fuelPricePerLiter: 0.95 },
  { countryCode: 'CA', countryName: 'Canada', currency: 'CAD', currencySymbol: 'CA$', fuelPricePerLiter: 1.65 },
  { countryCode: 'MX', countryName: 'Mexico', currency: 'MXN', currencySymbol: 'MX$', fuelPricePerLiter: 24.20 },
  { countryCode: 'PR', countryName: 'Puerto Rico', currency: 'USD', currencySymbol: '$', fuelPricePerLiter: 0.92 },
  { countryCode: 'JM', countryName: 'Jamaica', currency: 'JMD', currencySymbol: 'J$', fuelPricePerLiter: 195.00 },
  { countryCode: 'BS', countryName: 'Bahamas', currency: 'BSD', currencySymbol: 'B$', fuelPricePerLiter: 1.40 },
  { countryCode: 'DO', countryName: 'Dominican Republic', currency: 'DOP', currencySymbol: 'RD$', fuelPricePerLiter: 72.00 },
  { countryCode: 'CU', countryName: 'Cuba', currency: 'CUP', currencySymbol: '₱', fuelPricePerLiter: 30.00 },
  { countryCode: 'HT', countryName: 'Haiti', currency: 'HTG', currencySymbol: 'G', fuelPricePerLiter: 130.00 },
  { countryCode: 'TT', countryName: 'Trinidad and Tobago', currency: 'TTD', currencySymbol: 'TT$', fuelPricePerLiter: 5.75 },
  { countryCode: 'BB', countryName: 'Barbados', currency: 'BBD', currencySymbol: 'Bds$', fuelPricePerLiter: 3.90 },
  { countryCode: 'CR', countryName: 'Costa Rica', currency: 'CRC', currencySymbol: '₡', fuelPricePerLiter: 710.00 },
  { countryCode: 'PA', countryName: 'Panama', currency: 'PAB', currencySymbol: 'B/.', fuelPricePerLiter: 1.05 },
  { countryCode: 'GT', countryName: 'Guatemala', currency: 'GTQ', currencySymbol: 'Q', fuelPricePerLiter: 8.50 },
  { countryCode: 'HN', countryName: 'Honduras', currency: 'HNL', currencySymbol: 'L', fuelPricePerLiter: 28.00 },
  { countryCode: 'SV', countryName: 'El Salvador', currency: 'USD', currencySymbol: '$', fuelPricePerLiter: 1.10 },
  { countryCode: 'NI', countryName: 'Nicaragua', currency: 'NIO', currencySymbol: 'C$', fuelPricePerLiter: 49.00 },
  { countryCode: 'BZ', countryName: 'Belize', currency: 'BZD', currencySymbol: 'BZ$', fuelPricePerLiter: 3.40 },

  // South America
  { countryCode: 'BR', countryName: 'Brazil', currency: 'BRL', currencySymbol: 'R$', fuelPricePerLiter: 5.90 },
  { countryCode: 'AR', countryName: 'Argentina', currency: 'ARS', currencySymbol: '$', fuelPricePerLiter: 1050.00 },
  { countryCode: 'CO', countryName: 'Colombia', currency: 'COP', currencySymbol: '$', fuelPricePerLiter: 3950.00 },
  { countryCode: 'CL', countryName: 'Chile', currency: 'CLP', currencySymbol: '$', fuelPricePerLiter: 1250.00 },
  { countryCode: 'PE', countryName: 'Peru', currency: 'PEN', currencySymbol: 'S/', fuelPricePerLiter: 4.80 },
  { countryCode: 'EC', countryName: 'Ecuador', currency: 'USD', currencySymbol: '$', fuelPricePerLiter: 0.65 },
  { countryCode: 'VE', countryName: 'Venezuela', currency: 'VES', currencySymbol: 'Bs.', fuelPricePerLiter: 0.50 },
  { countryCode: 'BO', countryName: 'Bolivia', currency: 'BOB', currencySymbol: 'Bs', fuelPricePerLiter: 3.74 },
  { countryCode: 'PY', countryName: 'Paraguay', currency: 'PYG', currencySymbol: '₲', fuelPricePerLiter: 7800.00 },
  { countryCode: 'UY', countryName: 'Uruguay', currency: 'UYU', currencySymbol: '$U', fuelPricePerLiter: 77.00 },
  { countryCode: 'GY', countryName: 'Guyana', currency: 'GYD', currencySymbol: 'G$', fuelPricePerLiter: 215.00 },
  { countryCode: 'SR', countryName: 'Suriname', currency: 'SRD', currencySymbol: 'Sr$', fuelPricePerLiter: 42.00 },

  // Europe (Western, Central & Eastern)
  { countryCode: 'GB', countryName: 'United Kingdom', currency: 'GBP', currencySymbol: '£', fuelPricePerLiter: 1.45 },
  { countryCode: 'DE', countryName: 'Germany', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.78 },
  { countryCode: 'FR', countryName: 'France', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.82 },
  { countryCode: 'IT', countryName: 'Italy', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.86 },
  { countryCode: 'ES', countryName: 'Spain', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.62 },
  { countryCode: 'NL', countryName: 'Netherlands', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 2.02 },
  { countryCode: 'CH', countryName: 'Switzerland', currency: 'CHF', currencySymbol: 'CHF', fuelPricePerLiter: 1.80 },
  { countryCode: 'SE', countryName: 'Sweden', currency: 'SEK', currencySymbol: 'kr', fuelPricePerLiter: 18.50 },
  { countryCode: 'NO', countryName: 'Norway', currency: 'NOK', currencySymbol: 'kr', fuelPricePerLiter: 21.00 },
  { countryCode: 'DK', countryName: 'Denmark', currency: 'DKK', currencySymbol: 'kr', fuelPricePerLiter: 14.20 },
  { countryCode: 'FI', countryName: 'Finland', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.88 },
  { countryCode: 'BE', countryName: 'Belgium', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.72 },
  { countryCode: 'AT', countryName: 'Austria', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.60 },
  { countryCode: 'IE', countryName: 'Ireland', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.76 },
  { countryCode: 'PT', countryName: 'Portugal', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.70 },
  { countryCode: 'PL', countryName: 'Poland', currency: 'PLN', currencySymbol: 'zł', fuelPricePerLiter: 6.45 },
  { countryCode: 'CZ', countryName: 'Czech Republic', currency: 'CZK', currencySymbol: 'Kč', fuelPricePerLiter: 38.50 },
  { countryCode: 'HU', countryName: 'Hungary', currency: 'HUF', currencySymbol: 'Ft', fuelPricePerLiter: 605.00 },
  { countryCode: 'RO', countryName: 'Romania', currency: 'RON', currencySymbol: 'lei', fuelPricePerLiter: 7.25 },
  { countryCode: 'GR', countryName: 'Greece', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.90 },
  { countryCode: 'UA', countryName: 'Ukraine', currency: 'UAH', currencySymbol: '₴', fuelPricePerLiter: 56.00 },
  { countryCode: 'RU', countryName: 'Russia', currency: 'RUB', currencySymbol: '₽', fuelPricePerLiter: 58.00 },
  { countryCode: 'BG', countryName: 'Bulgaria', currency: 'BGN', currencySymbol: 'лв', fuelPricePerLiter: 2.65 },
  { countryCode: 'HR', countryName: 'Croatia', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.55 },
  { countryCode: 'RS', countryName: 'Serbia', currency: 'RSD', currencySymbol: 'дин', fuelPricePerLiter: 195.00 },
  { countryCode: 'SK', countryName: 'Slovakia', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.62 },
  { countryCode: 'SI', countryName: 'Slovenia', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.52 },
  { countryCode: 'LT', countryName: 'Lithuania', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.50 },
  { countryCode: 'LV', countryName: 'Latvia', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.65 },
  { countryCode: 'EE', countryName: 'Estonia', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.68 },
  { countryCode: 'IS', countryName: 'Iceland', currency: 'ISK', currencySymbol: 'kr', fuelPricePerLiter: 310.00 },
  { countryCode: 'LU', countryName: 'Luxembourg', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.58 },
  { countryCode: 'CY', countryName: 'Cyprus', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.48 },
  { countryCode: 'MT', countryName: 'Malta', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.34 },
  { countryCode: 'AL', countryName: 'Albania', currency: 'ALL', currencySymbol: 'L', fuelPricePerLiter: 180.00 },
  { countryCode: 'MK', countryName: 'North Macedonia', currency: 'MKD', currencySymbol: 'ден', fuelPricePerLiter: 81.50 },
  { countryCode: 'BA', countryName: 'Bosnia and Herzegovina', currency: 'BAM', currencySymbol: 'KM', fuelPricePerLiter: 2.65 },
  { countryCode: 'ME', countryName: 'Montenegro', currency: 'EUR', currencySymbol: '€', fuelPricePerLiter: 1.55 },
  { countryCode: 'MD', countryName: 'Moldova', currency: 'MDL', currencySymbol: 'L', fuelPricePerLiter: 24.50 },
  { countryCode: 'BY', countryName: 'Belarus', currency: 'BYN', currencySymbol: 'Br', fuelPricePerLiter: 2.40 },
  { countryCode: 'GE', countryName: 'Georgia', currency: 'GEL', currencySymbol: '₾', fuelPricePerLiter: 3.10 },
  { countryCode: 'AM', countryName: 'Armenia', currency: 'AMD', currencySymbol: '֏', fuelPricePerLiter: 490.00 },
  { countryCode: 'AZ', countryName: 'Azerbaijan', currency: 'AZN', currencySymbol: '₼', fuelPricePerLiter: 1.10 },
  { countryCode: 'KZ', countryName: 'Kazakhstan', currency: 'KZT', currencySymbol: '₸', fuelPricePerLiter: 215.00 },
  { countryCode: 'UZ', countryName: 'Uzbekistan', currency: 'UZS', currencySymbol: 'soʻm', fuelPricePerLiter: 10500.00 },
  { countryCode: 'KG', countryName: 'Kyrgyzstan', currency: 'KGS', currencySymbol: 'с', fuelPricePerLiter: 70.00 },
  { countryCode: 'TJ', countryName: 'Tajikistan', currency: 'TJS', currencySymbol: 'SM', fuelPricePerLiter: 10.50 },
  { countryCode: 'TM', countryName: 'Turkmenistan', currency: 'TMT', currencySymbol: 'T', fuelPricePerLiter: 1.50 },

  // Oceania
  { countryCode: 'AU', countryName: 'Australia', currency: 'AUD', currencySymbol: 'A$', fuelPricePerLiter: 1.85 },
  { countryCode: 'NZ', countryName: 'New Zealand', currency: 'NZD', currencySymbol: 'NZ$', fuelPricePerLiter: 2.65 },
  { countryCode: 'FJ', countryName: 'Fiji', currency: 'FJD', currencySymbol: 'FJ$', fuelPricePerLiter: 2.90 },
  { countryCode: 'PG', countryName: 'Papua New Guinea', currency: 'PGK', currencySymbol: 'K', fuelPricePerLiter: 4.50 },
  { countryCode: 'WS', countryName: 'Samoa', currency: 'WST', currencySymbol: 'WS$', fuelPricePerLiter: 3.20 },
  { countryCode: 'TO', countryName: 'Tonga', currency: 'TOP', currencySymbol: 'T$', fuelPricePerLiter: 2.95 },
  { countryCode: 'VU', countryName: 'Vanuatu', currency: 'VUV', currencySymbol: 'VT', fuelPricePerLiter: 190.00 },
  { countryCode: 'SB', countryName: 'Solomon Islands', currency: 'SBD', currencySymbol: 'SI$', fuelPricePerLiter: 11.50 },

  // Africa
  { countryCode: 'ZA', countryName: 'South Africa', currency: 'ZAR', currencySymbol: 'R', fuelPricePerLiter: 23.50 },
  { countryCode: 'NG', countryName: 'Nigeria', currency: 'NGN', currencySymbol: '₦', fuelPricePerLiter: 950.00 },
  { countryCode: 'EG', countryName: 'Egypt', currency: 'EGP', currencySymbol: 'E£', fuelPricePerLiter: 15.00 },
  { countryCode: 'KE', countryName: 'Kenya', currency: 'KES', currencySymbol: 'KSh', fuelPricePerLiter: 190.00 },
  { countryCode: 'GH', countryName: 'Ghana', currency: 'GHS', currencySymbol: 'GH₵', fuelPricePerLiter: 14.50 },
  { countryCode: 'MA', countryName: 'Morocco', currency: 'MAD', currencySymbol: 'DH', fuelPricePerLiter: 14.20 },
  { countryCode: 'DZ', countryName: 'Algeria', currency: 'DZD', currencySymbol: 'DA', fuelPricePerLiter: 45.00 },
  { countryCode: 'TN', countryName: 'Tunisia', currency: 'TND', currencySymbol: 'DT', fuelPricePerLiter: 2.50 },
  { countryCode: 'ET', countryName: 'Ethiopia', currency: 'ETB', currencySymbol: 'Br', fuelPricePerLiter: 85.00 },
  { countryCode: 'UG', countryName: 'Uganda', currency: 'UGX', currencySymbol: 'USh', fuelPricePerLiter: 5400.00 },
  { countryCode: 'TZ', countryName: 'Tanzania', currency: 'TZS', currencySymbol: 'TSh', fuelPricePerLiter: 3100.00 },
  { countryCode: 'RW', countryName: 'Rwanda', currency: 'RWF', currencySymbol: 'FRw', fuelPricePerLiter: 1650.00 },
  { countryCode: 'SN', countryName: 'Senegal', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 990.00 },
  { countryCode: 'CI', countryName: 'Ivory Coast', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 875.00 },
  { countryCode: 'CM', countryName: 'Cameroon', currency: 'XAF', currencySymbol: 'FCFA', fuelPricePerLiter: 840.00 },
  { countryCode: 'AO', countryName: 'Angola', currency: 'AOA', currencySymbol: 'Kz', fuelPricePerLiter: 300.00 },
  { countryCode: 'ZM', countryName: 'Zambia', currency: 'ZMW', currencySymbol: 'ZK', fuelPricePerLiter: 32.50 },
  { countryCode: 'ZW', countryName: 'Zimbabwe', currency: 'USD', currencySymbol: '$', fuelPricePerLiter: 1.60 },
  { countryCode: 'MZ', countryName: 'Mozambique', currency: 'MZN', currencySymbol: 'MT', fuelPricePerLiter: 86.00 },
  { countryCode: 'BW', countryName: 'Botswana', currency: 'BWP', currencySymbol: 'P', fuelPricePerLiter: 14.80 },
  { countryCode: 'NA', countryName: 'Namibia', currency: 'NAD', currencySymbol: 'N$', fuelPricePerLiter: 22.50 },
  { countryCode: 'MU', countryName: 'Mauritius', currency: 'MUR', currencySymbol: 'Rs', fuelPricePerLiter: 66.20 },
  { countryCode: 'LY', countryName: 'Libya', currency: 'LYD', currencySymbol: 'LD', fuelPricePerLiter: 0.15 },
  { countryCode: 'SD', countryName: 'Sudan', currency: 'SDG', currencySymbol: 'SDG', fuelPricePerLiter: 1800.00 },
  { countryCode: 'MG', countryName: 'Madagascar', currency: 'MGA', currencySymbol: 'Ar', fuelPricePerLiter: 5900.00 },
  { countryCode: 'MW', countryName: 'Malawi', currency: 'MWK', currencySymbol: 'MK', fuelPricePerLiter: 2500.00 },
  { countryCode: 'ML', countryName: 'Mali', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 850.00 },
  { countryCode: 'BF', countryName: 'Burkina Faso', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 850.00 },
  { countryCode: 'NE', countryName: 'Niger', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 540.00 },
  { countryCode: 'GN', countryName: 'Guinea', currency: 'GNF', currencySymbol: 'FG', fuelPricePerLiter: 12000.00 },
  { countryCode: 'SL', countryName: 'Sierra Leone', currency: 'SLE', currencySymbol: 'Le', fuelPricePerLiter: 30.00 },
  { countryCode: 'LR', countryName: 'Liberia', currency: 'USD', currencySymbol: '$', fuelPricePerLiter: 1.15 },
  { countryCode: 'TG', countryName: 'Togo', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 700.00 },
  { countryCode: 'BJ', countryName: 'Benin', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 680.00 },
  { countryCode: 'GA', countryName: 'Gabon', currency: 'XAF', currencySymbol: 'FCFA', fuelPricePerLiter: 605.00 },
  { countryCode: 'CG', countryName: 'Republic of the Congo', currency: 'XAF', currencySymbol: 'FCFA', fuelPricePerLiter: 625.00 },
  { countryCode: 'CD', countryName: 'DR Congo', currency: 'CDF', currencySymbol: 'FC', fuelPricePerLiter: 3200.00 },
  { countryCode: 'SO', countryName: 'Somalia', currency: 'USD', currencySymbol: '$', fuelPricePerLiter: 1.05 },
  { countryCode: 'DJ', countryName: 'Djibouti', currency: 'DJF', currencySymbol: 'Fdj', fuelPricePerLiter: 350.00 },
  { countryCode: 'ER', countryName: 'Eritrea', currency: 'ERN', currencySymbol: 'Nfk', fuelPricePerLiter: 35.00 },
  { countryCode: 'SS', countryName: 'South Sudan', currency: 'SSP', currencySymbol: '£', fuelPricePerLiter: 1400.00 },
  { countryCode: 'TD', countryName: 'Chad', currency: 'XAF', currencySymbol: 'FCFA', fuelPricePerLiter: 730.00 },
  { countryCode: 'CF', countryName: 'Central African Republic', currency: 'XAF', currencySymbol: 'FCFA', fuelPricePerLiter: 1100.00 },
  { countryCode: 'MR', countryName: 'Mauritania', currency: 'MRU', currencySymbol: 'UM', fuelPricePerLiter: 56.00 },
  { countryCode: 'GM', countryName: 'Gambia', currency: 'GMD', currencySymbol: 'D', fuelPricePerLiter: 77.00 },
  { countryCode: 'GW', countryName: 'Guinea-Bissau', currency: 'XOF', currencySymbol: 'CFA', fuelPricePerLiter: 850.00 },
  { countryCode: 'CV', countryName: 'Cape Verde', currency: 'CVE', currencySymbol: 'Esc', fuelPricePerLiter: 145.00 },
  { countryCode: 'ST', countryName: 'Sao Tome and Principe', currency: 'STN', currencySymbol: 'Db', fuelPricePerLiter: 35.00 },
  { countryCode: 'GQ', countryName: 'Equatorial Guinea', currency: 'XAF', currencySymbol: 'FCFA', fuelPricePerLiter: 595.00 },
  { countryCode: 'BI', countryName: 'Burundi', currency: 'BIF', currencySymbol: 'FBu', fuelPricePerLiter: 4000.00 },
  { countryCode: 'SC', countryName: 'Seychelles', currency: 'SCR', currencySymbol: 'SR', fuelPricePerLiter: 22.50 },
  { countryCode: 'KM', countryName: 'Comoros', currency: 'KMF', currencySymbol: 'CF', fuelPricePerLiter: 750.00 },
  { countryCode: 'LS', countryName: 'Lesotho', currency: 'LSL', currencySymbol: 'M', fuelPricePerLiter: 21.00 },
  { countryCode: 'SZ', countryName: 'Eswatini', currency: 'SZL', currencySymbol: 'E', fuelPricePerLiter: 21.50 }
];

async function seed() {
  console.log(`🚀 Seeding ${GLOBAL_COUNTRY_FUEL_DATA.length} country fuel rates...`);
  let created = 0;
  let updated = 0;

  for (const item of GLOBAL_COUNTRY_FUEL_DATA) {
    const res = await prisma.countryFuelRate.upsert({
      where: { countryCode: item.countryCode },
      create: {
        countryCode: item.countryCode,
        countryName: item.countryName,
        currency: item.currency,
        currencySymbol: item.currencySymbol,
        fuelPricePerLiter: item.fuelPricePerLiter,
        isActive: true
      },
      update: {
        countryName: item.countryName,
        currency: item.currency,
        currencySymbol: item.currencySymbol,
        fuelPricePerLiter: item.fuelPricePerLiter,
        isActive: true
      }
    });
    if (res) created++;
  }

  const count = await prisma.countryFuelRate.count();
  console.log(`✅ Finished seeding! Total CountryFuelRate rows in DB: ${count}`);
}

seed().catch(console.error).finally(() => prisma.$disconnect());
